// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __GPD_BOOKKEEPING_H__
#define __GPD_BOOKKEEPING_H__



#endif // __GPD_BOOKKEEPING_H__
