// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include "gpd-components-common.h"


/** @brief Called to get the application information payload from application. This callback
 *         helps application to filled up the application specefic application information
 *         that gets transmitted.
 *
 * @param messagePayload The pointer for the user to fillup.
 * @param maxLength maximum length.
 * @param last indicates the present application description packet is the last one.
 * Ver.: always
 *
 * @return the length writen by application.
 */
uint8_t emberGpdAfPluginGetApplicationDescriptionCallback(uint8_t * messagePayload,
                                                          uint8_t maxLength,
                                                          bool * last)
{
  // This is an example of how to fill up an occupany sensor report as application description
  // The following is a single report descriptor for the occupancy attribute.
  uint8_t appDesc[13] = {0x01, 0x01, 0x00, 0x00, 0x07, 0x08, 0x06, 0x04, 0x00, 0x00, 0x18, 0x10, 0x00};
  memcpy (messagePayload, appDesc, sizeof(appDesc));
  *last = true;
  return sizeof(appDesc);
}


/** @brief This is called by framework to receive a contact status in case of generic switch
 *         info during commissioning request.
 *
 * @return a 8bit switch contact status.
 */
uint8_t emberGpdAfPluginGetSwitchContactStutusCallback(void)
{
  return 0;
}


/** @brief Called from the imcomming command handler context for all the incoming
 *         command before the command handler handles it. based on the return code
 *         of this callback the internal command handler skips the processing.
 *
 * @param gpdCommand CommandId.
 * @param length length of the command
 * @param commandPayload The pointer to the commissioning reply payload.
 * Ver.: always
 *
 * @return true if application handled it.
 */
bool emberGpdAfPluginIncomingCommandCallback(uint8_t gpdCommand,
                                            uint8_t length,
                                            uint8_t * commandPayload)
{
  return false;
}


/** @brief This is called by the application state machine to indicate when the GPD is going to sleep.
 *         Typically this will be called from rx-after-tx state machines and application state machine.
 *
 */
void emberGpdAfPluginSleepCallback(void)
{
}


/** @brief This is called by framework to get a random number. User should implement it appropriately
 * depending on the random number generation in the project.
 *
 * @return a 32bit random number.
 */
uint32_t emberGpdAfPluginGetRandomCallback(void)
{
  volatile uint32_t randomValue;
  return randomValue;
}


