// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __GPD_CONFIG__
#define __GPD_CONFIG__




// Top level macros
#define EMBER_AF_DEVICE_NAME "gpdMG12v662"


// Generated plugin macros

// Use this macro to check if GPD App Configuration plugin is included
#define EMBER_AF_PLUGIN_APPS
// User options for plugin GPD App Configuration
#define EMBER_AF_PLUGIN_APPS_APP_DEVICE_ID 2
#define EMBER_AF_PLUGIN_APPS_APP_CHANNEL_SET { 11, 15, 20, 24, 25, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 26 }
#define EMBER_AF_PLUGIN_APPS_APP_CHANNEL_SET_LENGTH (16)
#define EMBER_AF_PLUGIN_APPS_APPLICATION_ID EMBER_GPD_APP_ID_SRC_ID
#define EMBER_AF_PLUGIN_APPS_SRC_ID 305419896
#define EMBER_AF_PLUGIN_APPS_GPD_ENDPOINT 99
#define EMBER_AF_PLUGIN_APPS_MAC_SEQ EMBER_GPD_MAC_SEQ_INCREMETAL
#define EMBER_AF_PLUGIN_APPS_BIDIR_CAPABLE true
#define EMBER_AF_PLUGIN_APPS_RX_OFFSET 20
#define EMBER_AF_PLUGIN_APPS_RX_WINDOW 10
#define EMBER_AF_PLUGIN_APPS_RX_CAPABILITY true
#define EMBER_AF_PLUGIN_APPS_PAN_ID_REQUEST false
#define EMBER_AF_PLUGIN_APPS_SECURITY_LEVEL EMBER_GPD_SECURITY_LEVEL_LONG_FULL
#define EMBER_AF_PLUGIN_APPS_SECURITY_KEY_TYPE EMBER_GPD_SECURITY_KEY_TYPE_OOB
#define EMBER_AF_PLUGIN_APPS_KEY { 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff }
#define EMBER_AF_PLUGIN_APPS_KEY_LENGTH (16)
#define EMBER_AF_PLUGIN_APPS_KEY_REQUEST true
#define EMBER_AF_PLUGIN_APPS_KEY_ENCRYPT true
#define EMBER_AF_PLUGIN_APPS_FIXED_LOCATION true
#define EMBER_AF_PLUGIN_APPS_APP_INFO false
#define EMBER_AF_PLUGIN_APPS_GPD_APP_NUMBER_OF_CHANNEL_REQUEST_PER_CHANNEL_WITH_AC_SET 4
#define EMBER_AF_PLUGIN_APPS_GPD_APP_NUMBER_OF_CHANNEL_REQUEST_PER_CHANNEL 4
#define EMBER_AF_PLUGIN_APPS_GPD_APP_NUMBER_OF_COMMISSIONING_REQUEST 4

// Use this macro to check if Radio Coexistence Stub plugin is included
#define EMBER_AF_PLUGIN_COEXISTENCE_STUB

// Use this macro to check if GPD Components plugin is included
#define EMBER_AF_PLUGIN_GPD_COMPONENTS

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_GPD_HAL

// Use this macro to check if mbed TLS Common plugin is included
#define EMBER_AF_PLUGIN_GPD_MBEDTLS

// Use this macro to check if mbed TLS Multiprotocol Configuration plugin is included
#define EMBER_AF_PLUGIN_GPD_MBEDTLS_CONFIG

// Use this macro to check if GPD App Startup plugin is included
#define EMBER_AF_PLUGIN_GPD_STARTUP

// Use this macro to check if PS Store plugin is included
#define EMBER_AF_PLUGIN_PSSTORE

// Use this macro to check if RAIL Library plugin is included
#define EMBER_AF_PLUGIN_RAIL_LIBRARY
// User options for plugin RAIL Library
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_RAILPHYDEF 1


// Generated API headers

// API coexistence from Radio Coexistence Stub plugin
#define EMBER_AF_API_COEXISTENCE "../../../projects/Simplicity Studio 04-19/Simplicity Studio.app/Contents/Eclipse/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154/coexistence-802154.h"

// API psstore from PS Store plugin
#define EMBER_AF_API_PSSTORE "../../../projects/Simplicity Studio 04-19/Simplicity Studio.app/Contents/Eclipse/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/psstore/store.h"

// API rail-library from RAIL Library plugin
#define EMBER_AF_API_RAIL_LIBRARY "../../../projects/Simplicity Studio 04-19/Simplicity Studio.app/Contents/Eclipse/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/common/rail.h"


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG12P332F1024GL125

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 2

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 332

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 1024K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE L

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 125

#ifdef EMBER_AF_RADIO_MODULE
#undef EMBER_AF_RADIO_MODULE
#endif
#define EMBER_AF_RADIO_MODULE XX

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG12P332F1024GL125

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 2

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 332

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 1024K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE L

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 125

#ifdef EMBER_AF_MCU_MODULE
#undef EMBER_AF_MCU_MODULE
#endif
#define EMBER_AF_MCU_MODULE XX

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4162A



#endif // __GPD_CONFIG__
